version: '3'
services:
  writeDB:
    image: postgres:14.4
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${WRITE_DB_PASSWORD}
      POSTGRES_DB: ${WRITE_DB_NAME}
    container_name: writeDB
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./db/seed.sql:/seed.sql
