version: '3'
services:
  writeDB:
    image: postgres:14.4
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${WRITE_DB_PASSWORD}
      POSTGRES_DB: ${WRITE_DB_NAME}
    container_name: writeDB
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./db/seed.sql:/seed.sql

  readDB:
    image: surrealdb/surrealdb:latest
    container_name: readDB
    restart: always
    command: start --user ${READ_DB_USER} --pass ${READ_DB_PASSWORD} file:/data/database.db
    ports:
      - 443:8000
    volumes:
      - ./data:/data

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    ports:
      - 5672:5672

  datasync:
    container_name: datasync
    build:
      context: ./apps/datasync
      dockerfile: Dockerfile
      target: development
    command: npm run start:datasync
    env_file:
      - ./apps/datasync/.env
    depends_on:
      - readDB
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - usr/src/app/node_modules

  api:
    container_name: api
    build:
      context: ./apps/api
      dockerfile: Dockerfile
      target: development
    command: npm start
    env_file:
      - ./apps/api/.env
    depends_on:
      - readDB
      - writeDB
      - rabbitmq
      - datasync
    volumes:
      - .:/usr/src/app
      - usr/src/app/node_modules
    ports:
      - 3000:3000
